name       : tepl
version    : 3.0.0
release    : 1
source     :
    - https://download.gnome.org/sources/tepl/3.0/tepl-3.0.0.tar.xz : 9eb6fceb0b521de7bf684508138a5b8428d9f575c395ba54f9e31597980fd0ef
license    : LGPL-2.1
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(uchardet)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
