name       : tepl
version    : 6.2.0
release    : 16
source     :
    - https://gitlab.gnome.org/swilmet/tepl/-/archive/6.2.0/tepl-6.2.0.tar.gz : c9cb32d19a2112d5defceb9e85913af199e576407c3ace2ee24fcf7334dd14d3
homepage   : https://gitlab.gnome.org/swilmet/tepl
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(icu-io)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
