name       : tepl
version    : 6.0.2
release    : 13
source     :
    - https://download.gnome.org/sources/tepl/6.0/tepl-6.0.2.tar.xz : 5b4a9c6c61bd000553ef9799f4ca625d05f5801036fb2c2f928a49448c903c09
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(icu-io)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
