name       : tepl
version    : 4.2.1
release    : 4
source     :
    - https://download.gnome.org/sources/tepl/4.2/tepl-4.2.1.tar.xz : f31ce335fa69061e5ab8653842c5d9c763641abbe323cc2374c273fc240d2b6e
license    : LGPL-2.1
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(uchardet)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
