name       : tepl
version    : 6.4.0
release    : 17
source     :
    - https://gitlab.gnome.org/swilmet/tepl/-/archive/6.4.0/tepl-6.4.0.tar.gz : d42eb15490290b9a7047812f76035dd1c43449c0ab41a2c5db26ba832a7ca761
homepage   : https://gitlab.gnome.org/swilmet/tepl
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(icu-io)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
