name       : tepl
version    : 4.2.0
release    : 3
source     :
    - https://download.gnome.org/sources/tepl/4.2/tepl-4.2.0.tar.xz : 8839d4428ecdd87fd5abc657ebbe5a9601a57262e9946845e47dec264e669ccd
license    : LGPL-2.1
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(uchardet)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
