name       : tepl
version    : '6.0'
release    : 9
source     :
    - https://download.gnome.org/sources/tepl/6.00/tepl-6.00.0.tar.xz : a86397a895dca9c0de7a5ccb063bda8f7ef691cccb950ce2cfdee367903e7a63
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(icu-io)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
