name       : tepl
version    : 5.1.1
release    : 7
source     :
    - https://download.gnome.org/sources/tepl/5.1/tepl-5.1.1.tar.xz : 9a8099557db72f0e569ad66ee6470059b7244f65f233736fbd0dc85d5e81da42
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text
    editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(icu-io)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
