name       : tepl
version    : 4.4.0
release    : 5
source     :
    - https://download.gnome.org/sources/tepl/4.4/tepl-4.4.0.tar.xz : e6f6673a8a27e8f280725db8fbacec79b20676ae0558755239d15a9808faa256
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(amtk-5)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(uchardet)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
